name: build

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bear

      - if: runner.os == 'macOS'
        run: |
          brew install make bear
          echo "PATH=$(brew --prefix make)/libexec/gnubin:$PATH" >> $GITHUB_ENV

      - run: |
          if command -v gmake >/dev/null; then
            gmake debug
          else
            make debug
          fi
        shell: bash

      - run: |
          if command -v gmake >/dev/null; then
            gmake test
          else
            make test
          fi
        shell: bash
