name: build

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - if: runner.os == 'macOS'
        run: |
          brew install make
          echo "PATH=$(brew --prefix make)/libexec/gnubin:$PATH" >> $GITHUB_ENV

      - run: |
          if command -v gmake >/dev/null; then
            gmake build
          else
            make build
          fi
        shell: bash
